- name: Deploy Flask App to App Servers
  hosts: appservers
  become: yes
  tasks:
    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Flask
      pip:
        name: flask
        executable: pip3

    - name: Create app directory
      file:
        path: /home/{{ ansible_user }}/flask-app
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy Flask app
      copy:
        src: flask-app/app.py
        dest: /home/{{ ansible_user }}/flask-app/app.py
        mode: '0755'

    - name: Kill any running Flask process (if present)
      shell: pkill -f "python3 /home/{{ ansible_user }}/flask-app/app.py"
      ignore_errors: yes

    - name: Run Flask app (simple background mode)
      shell: nohup python3 /home/{{ ansible_user }}/flask-app/app.py > /dev/null 2>&1 &
      args:
        chdir: /home/{{ ansible_user }}/flask-app
