- name: Configure NGINX load balancer
  hosts: loadbalancer
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy custom NGINX config
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
        enabled: yes
